### PR TITLE
Adds the option to display the default image instead of the CORE name when the image is missing

### PR DESCRIPTION
**Pull request by neil-morrison44**
- I figure most users won't have an image for every core so this provides a way to see something nice
- Might also add in some logic so an (optional) file named `default.whatever` takes the place of the MiSTer eyes, would be handy for folks who want to customise their setup
- Also adds a `.clang-format` (Google but with tabs instead of spaces) but only auto-formats the files I touched

### CODE REVIEW

**Comment by neil-morrison44** [comment]
@FeralAI do you see any issues with the optional default image change? (it would mean reading an image from the filesystem before it currently does it, then falling back to the MiSTer eyes if there's not one there)

---

Just noticed `config.startupImage`, ~~I think the `default.whatever` approach might be a bit cleaner (especially if it gets used in 2 places)~~ will have it reuse it

**Comment by FeralAI** [comment]
> @FeralAI do you see any issues with the optional default image change? (it would mean reading an image from the filesystem before it currently does it, then falling back to the MiSTer eyes if there's not one there)
> 
> Just noticed `config.startupImage`, ~I think the `default.whatever` approach might be a bit cleaner (especially if it gets used in 2 places)~ will have it reuse it

I think they could be 2 different options if we want them to be. I could see someone wanting a distinct animation/image on startup and a separate image for fallback stuff. If you want to go easy we can just link startup to it for now.

**Comment by neil-morrison44** [comment]
Yeah that's along the lines I'm thinking - just trying to work out a nice way to get the choice to be `TEXT` / `the start up image` / `some other image` in as few config options as I can

**Comment by neil-morrison44** [comment]
That's it using `missingCoreImage` now, which can either be set to `""` for text, `"startup"` to use the startup image (including the default eyes), or any image path.

---

I also chucked in a `CMDRLCONF` which just loads the config again since I couldn't be bothered unplugging it -- ideally it should poll the toml file for changes (somehow)

**Comment by FeralAI** [comment]
I'm going to branch for some documentation updates. Want me to add these?

**Pull request merged**
