### PR TITLE
Documenation updates

### PR DESCRIPTION
**Pull request by FeralAI**
Not ready yet, just starting to refine the current documentation. Added basic wiring diagrams for the Sparkfun boards.

I'm thinking the README might be a little overwhelming and should probably be streamlined and the more detailed info gets broken out to its own page. Can either do this in the repo or we can start up a wiki.

Thoughts? Did you already have some plans for the documentation stucture?

### CODE REVIEW

**Comment by neil-morrison44** [comment]
My plans with the docs are, in the root README:

- have gifs of the RoundyPi in its case (maybe as part of the MiSTercade too) showing different cores loading / the fancy gifs looping.
- Have a very quick start guide including things like using the RoundyPi, loading the UF2, setting up the scripts, loading images, using a right angle micro-USB cable, printing the case, changing some config options etc
- Deep linking to sections in this .md file (or multiple, or a wiki, whichever suits) for "advanced" topics (non-RoundyPi boards, different screens, more config options etc)
- just having the micropython version as a footnote (will move it into its own folder sometime soon)

**Comment by FeralAI** [comment]
OK cool. I can break out the advanced sections which will leave the beginnings of the streamlined quick start. I like the wiki idea. There's enough info here to justify it along with allowing easy navigation between the docs.

**Comment by FeralAI** [comment]
README is stripped down and content is in the wiki. Will do more cleanup/organization on the wiki a bit later when I get back.

If we're keeping the Arduino README where it is for now this PR is ready for review.

**Comment by neil-morrison44** [comment]
👍🏻 looks great, I'll juggle the READMEs around when I've got gifs etc of it all set up to put in them

**Comment by neil-morrison44** [comment]
(merged when I could have approved there...)

One thing - I wonder if we should change either the default value of `missingCoreImage` or the section that says you need to tty into it to see the core names - since by default the cores will still be output to the display until the config's changed.

I wonder how much of an "advanced user" feature caring about the core name is

**Comment by FeralAI** [comment]
Yeah we likely don't need that section, was just porting from the original README. There's a list of core names here: https://mister-devel.github.io/MkDocs_MiSTer/developer/corenames/ where the `Internal Name` is what will be requested. For arcade games it just uses the zip file name from the ROM set. I can add something to the wiki regarding file names, unless you want that linked in the Quick Start?

EDIT: I'm going to copy the Quick Start to a wiki page and put the naming stuff in there. Will let us make revisions without repo commits until we're ready for it to go live.

**Pull request merged**
