### PR TITLE
Adds 3D models for the RoundyPi

### PR DESCRIPTION
**Pull request by neil-morrison44**
- Not been able to source a CAD file for the RoundyPi itself yet (or a particuarly good one for the display) so there'll be a lot of trial & error in getting this in
- Plan is:
  - A single "holding peice" for the RoundyPi which can either be screwed into the standalone case or the Multisystem dust cover (which are both yet to be started)
- Will need to leave room for a wide collection of right angle micro-USB cables
- Will likely need to loosen up the tolerances since the RoundyPi screen isn't perfectly aligned to the pcb (or at least mine isn't)

### CODE REVIEW

**Comment by FeralAI** [comment]
> * Not been able to source a CAD file for the RoundyPi itself yet (or a particuarly good one for the display) so there'll be a lot of trial & error in getting this in

Have you taken a look at the Waveshare module's model? https://www.waveshare.com/wiki/1.28inch_LCD_Module#3D_Drawing

> * Will likely need to loosen up the tolerances since the RoundyPi screen isn't perfectly aligned to the pcb (or at least mine isn't)

Same here. My screen is ever-so-slightly skewed to the left side of the board.

**Comment by neil-morrison44** [comment]
Yeah - the waveshare one's in the project already for the full size pico case - was hoping to get something closer to the RoundyPi, might end up reusing it but changing the stuff on top & adding the GPIO pins bit.

**Comment by neil-morrison44** [comment]
Having a few 3D printer issues which're slowing me down a bit with this - upgrading my way out of them...

**Comment by FeralAI** [comment]
> Having a few 3D printer issues which're slowing me down a bit with this - upgrading my way out of them...

That's a bummer. I know all too well how that goes (IDEX extruder upgrades, BLTouch, firmware hacking, ugh).

**Comment by neil-morrison44** [comment]
@FeralAI I'm fairly happy with where the models are with this now - the only things remaining are:

- some clean up of the `.scad` files (there's a bunch of stuff which should be shared)
- some renaming to make things clearer (screen.scad should be `front_plate` & gets reused so shouldn't be in "standalone")
- Wiki docs with printing tips etc

Also I need to print off the standalone stand to make sure it doesn't tip over... but the MultiSystem dust cover should be good to try on a real MultiSystem.

Few things to know:
- The dust cover has to be printed with supports for the bits where it attaches to the front plate (all the places with supports get hidden behind the screen anyway)
- Need 2x 12mm M2.5 screws to join the front plate & the cover & apply the pressure keeping the RoundyPi in place
- Need an angled microUSB cable (I got one that's reversible but it shouldn't matter too much with the multisystem print so long as it can fit through the hole & there's enough room inside to plug it in)

**Comment by FeralAI** [comment]
Noticed you added a few more commits. If this is ready I can try the Multisystem print tomorrow.

**Comment by neil-morrison44** [comment]
👍🏻 Multisystem one (inc. "face plate") should be ready for a proper try - I'm just tweaking the standalone stand to get it to more reliably stay upright regardless of what the USB cable does

**Comment by FeralAI** [comment]
Did a test print and aside from some slight bowing I have from my printer it came out pretty nice. One thing I noticed though is that it doesn't seem to fit like the original. In this picture (new on left, original on right) the original has some beveling or whatever that's called to slot into the grooves in the case:



So the only way I was able to get it to fit was to scoot it forward to the next slotted groove:



If that beveling is added then it should fit fine, though it will be recessed in front just a bit compared to the original. Whether that's aligned or not probably doesn't matter too much if a cable is running through the front.

Oh and the micro USB on my Roundy decided it no longer wanted to stay attached to the board. It had come loose a few weeks back with all the testing, but it just finally gave out 😩. I'm giving myself about a 50% chance at a successful repair 🤞

**Comment by neil-morrison44** [comment]
Any idea where to grab the .stl for that dust cover? (I think I got the `V2` one which must be older I guess, not sure if we'll need to support both).

Did you try the face plate stl?

---

That's annoying - I was wondering how strong the USB connector was (had been unplugging the other side of the USB more just incase)

**Comment by FeralAI** [comment]
Here's the V5 case, which I think is current: https://www.printables.com/model/159379-mister-multisystem-v5-2022-classic-gaming-console-/files
I did try the faceplace and it fit pretty well. There could be a little more room for the micro connector, though I'm not sure if you had a specific cable in mind. The GPIO did show a bit outside of the faceplace, but that wasn't a big deal. I can add a picture a little later.

Regarding the Roundy connector part of that was my fault because of how I had it mounted in my keyboard passthrough. Would have been great if it was mounted through the board, but I understand why they wouldn't/couldn't do that.

**Comment by neil-morrison44** [comment]
That's it using the V5 cover now, also cut a larger gap for any variation of micro-USB cable (the one I'm using is this: https://www.amazon.co.uk/gp/product/B07CBTVR8G though)

**Comment by FeralAI** [comment]
Sorry got busy earlier but here's what it looked like:




Going to try printing out the new version now.

**Comment by FeralAI** [comment]
Printer isn't cooperating today. I'll give it another shot in the morning.

**Comment by FeralAI** [comment]
Sorry about the delay in testing the print. Printer still wasn't working well the other day and didn't have time over the weekend. Going to give it another shot in a little bit here.

**Pull request merged**
